name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    #- name: Doxygen Action
    #  uses: mattnotmitt/doxygen-action@v1.9.3
    #  with:
    #  doxyfile-path: ./Doxyfile
    #  working-directory: .

    - run: >
        sudo apt-get install
        catch
        clang
        clang-tidy
        cmake
        dia
        doxygen
        graphviz
        libeigen3-dev
        llvm
        make
        wget

    - run: wget https://mirror.us-midwest-1.nexcess.net/gnu/gsl/gsl-2.7.1.tar.gz
    - run: tar fvx gsl-2.7.1.tar.gz
    - run: cd gsl-2.7.1; ./configure; make; make install
    - run: make
    - run: make doc

      # WARNING: Avoid installing 'publish_dir/.gitignore' in main branch if
      # purpose be to hide products of build in output of 'git status' and if
      # products be intended for gh-pages.  peaceiris's action works well, but
      # it will silently fail to deploy any files and/or directories mentioned
      # in 'publish_dir/.gitignore'.  In order to hide products of build on
      # main branch, put entry for 'publish_dir' into top-level '.gitignore'.
    - name: Deployment of GH-Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        enable_jekyll: false
        force_orphan: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs
