name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.3
      with:
        doxyfile-path: ./Doxyfile
        working-directory: .

    - run: sudo apt-get install catch cmake clang clang-tidy llvm make
    - run: sudo apt-get install dia doxygen graphviz
    - run: make

    - name: Top-Level GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        enable_jekyll: false
        force_orphan: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        keep_files: true  # Seems necessary for subdirectories to deploy.
        publish_branch: gh-pages
        publish_dir: ./docs
